import blueprintsJson from './design-blueprints.json';

/** Hand-authored seed catalogue — no lorem ipsum, no duplicate bios/titles. */

export type CreatorPersona = {
  username: string;
  displayName: string;
  bio: string;
  websitePath: string;
  /** 0 = niche, 1 = mid, 2 = popular */
  popularity: 0 | 1 | 2;
  homeCategories: string[];
  homeStyles: string[];
  homePlatforms: string[];
  homeIndustries: string[];
};

export type DesignBlueprint = {
  title: string;
  description: string;
  categorySlug: string;
  platform: string;
  industry: string;
  provenance: string;
  styleSlugs: string[];
  colourFamilies: string[];
  tagSlugs: string[];
};

export const CREATOR_PERSONAS: CreatorPersona[] = [
  {
    username: 'mira_halden',
    displayName: 'Mira Halden',
    bio: 'Mobile product designer chasing quieter empty states and honest type.',
    websitePath: 'mira-halden',
    popularity: 2,
    homeCategories: ['mobile-apps', 'health'],
    homeStyles: ['minimal', 'soft', 'accessible'],
    homePlatforms: ['ios', 'android'],
    homeIndustries: ['health', 'lifestyle'],
  },
  {
    username: 'jonah_velte',
    displayName: 'Jonah Velte',
    bio: 'Dashboard craftsman. I care about densities you can still read at dusk.',
    websitePath: 'jonahvelte',
    popularity: 2,
    homeCategories: ['dashboards', 'fintech'],
    homeStyles: ['data-dense', 'grid-based', 'functional'],
    homePlatforms: ['desktop-web', 'responsive-web'],
    homeIndustries: ['saas', 'fintech'],
  },
  {
    username: 'sable_orin',
    displayName: 'Sable Orin',
    bio: 'Editorial art director moonlighting in portfolio systems.',
    websitePath: 'sableorin',
    popularity: 2,
    homeCategories: ['editorial', 'portfolios'],
    homeStyles: ['editorial', 'serif', 'photography-led'],
    homePlatforms: ['responsive-web', 'print'],
    homeIndustries: ['media', 'lifestyle'],
  },
  {
    username: 'kenji_mora',
    displayName: 'Kenji Mora',
    bio: 'Brand systems for small studios. Marks that survive a bad fax.',
    websitePath: 'kenjimora',
    popularity: 1,
    homeCategories: ['branding', 'portfolios'],
    homeStyles: ['geometric', 'monochrome', 'swiss'],
    homePlatforms: ['brand-identity', 'print'],
    homeIndustries: ['media', 'education'],
  },
  {
    username: 'ada_quil',
    displayName: 'Ada Quil',
    bio: 'Commerce UI with a soft spine — conversion without shouting.',
    websitePath: 'adaquil',
    popularity: 2,
    homeCategories: ['ecommerce', 'web-apps'],
    homeStyles: ['conversion-focused', 'soft', 'responsive'],
    homePlatforms: ['responsive-web', 'ios'],
    homeIndustries: ['ecommerce', 'lifestyle'],
  },
  {
    username: 'rov_ansel',
    displayName: 'Rov Ansel',
    bio: 'Travel product designer collecting ferry schedules and weather type.',
    websitePath: 'rovansel',
    popularity: 1,
    homeCategories: ['travel', 'mobile-apps'],
    homeStyles: ['organic', 'muted-colour', 'mobile-first'],
    homePlatforms: ['ios', 'responsive-web'],
    homeIndustries: ['travel', 'lifestyle'],
  },
  {
    username: 'nell_briggs',
    displayName: 'Nell Briggs',
    bio: 'Social product designer allergic to infinite scroll theatrics.',
    websitePath: 'nellbriggs',
    popularity: 1,
    homeCategories: ['social', 'mobile-apps'],
    homeStyles: ['playful', 'bold-colour', 'minimal-navigation'],
    homePlatforms: ['ios', 'android'],
    homeIndustries: ['media', 'lifestyle'],
  },
  {
    username: 'theo_krane',
    displayName: 'Theo Krane',
    bio: 'Fintech interface lead. Trust is a typography problem.',
    websitePath: 'theokrane',
    popularity: 2,
    homeCategories: ['fintech', 'dashboards'],
    homeStyles: ['functional', 'high-contrast', 'sans-serif'],
    homePlatforms: ['responsive-web', 'desktop-web'],
    homeIndustries: ['fintech', 'saas'],
  },
  {
    username: 'isla_pern',
    displayName: 'Isla Pern',
    bio: 'Health UX designer focusing on calm forms and clear next steps.',
    websitePath: 'islapern',
    popularity: 1,
    homeCategories: ['health', 'mobile-apps'],
    homeStyles: ['accessible', 'soft', 'spacious'],
    homePlatforms: ['ios', 'tablet'],
    homeIndustries: ['health', 'education'],
  },
  {
    username: 'cass_ydro',
    displayName: 'Cass Ydro',
    bio: 'Experimental navigation studies and slightly crooked grids.',
    websitePath: 'cassydro',
    popularity: 0,
    homeCategories: ['experimental', 'web-apps'],
    homeStyles: ['experimental-navigation', 'brutalist', 'futuristic'],
    homePlatforms: ['desktop-web', 'responsive-web'],
    homeIndustries: ['media', 'saas'],
  },
  {
    username: 'leo_marsh',
    displayName: 'Leo Marsh',
    bio: 'Swiss grid devotee who still lets colour misbehave sometimes.',
    websitePath: 'leomarsh',
    popularity: 1,
    homeCategories: ['web-apps', 'branding'],
    homeStyles: ['swiss', 'grid-based', 'typographic'],
    homePlatforms: ['desktop-web', 'brand-identity'],
    homeIndustries: ['saas', 'education'],
  },
  {
    username: 'priya_noll',
    displayName: 'Priya Noll',
    bio: 'Illustration-led product work for education startups.',
    websitePath: 'priyanoll',
    popularity: 1,
    homeCategories: ['web-apps', 'mobile-apps'],
    homeStyles: ['illustration-led', 'playful', 'hand-drawn'],
    homePlatforms: ['responsive-web', 'ios'],
    homeIndustries: ['education', 'lifestyle'],
  },
  {
    username: 'owen_sail',
    displayName: 'Owen Sail',
    bio: 'Portfolio designer for architects who hate stock moodboards.',
    websitePath: 'owensail',
    popularity: 0,
    homeCategories: ['portfolios', 'editorial'],
    homeStyles: ['photography-led', 'minimal', 'content-first'],
    homePlatforms: ['responsive-web', 'print'],
    homeIndustries: ['media', 'lifestyle'],
  },
  {
    username: 'vera_moss',
    displayName: 'Vera Moss',
    bio: 'Luxury retail UI with restrained motion and wide margins.',
    websitePath: 'veramoss',
    popularity: 1,
    homeCategories: ['ecommerce', 'branding'],
    homeStyles: ['luxury', 'muted-colour', 'motion-led'],
    homePlatforms: ['responsive-web', 'ios'],
    homeIndustries: ['ecommerce', 'lifestyle'],
  },
  {
    username: 'hugo_flint',
    displayName: 'Hugo Flint',
    bio: 'Industrial interfaces for workshop tools and field tablets.',
    websitePath: 'hugoflint',
    popularity: 0,
    homeCategories: ['dashboards', 'mobile-apps'],
    homeStyles: ['industrial', 'high-contrast', 'functional'],
    homePlatforms: ['tablet', 'android'],
    homeIndustries: ['saas', 'education'],
  },
  {
    username: 'rina_kole',
    displayName: 'Rina Kole',
    bio: 'Y2K nostalgist designing social onboarding that feels handmade.',
    websitePath: 'rinakole',
    popularity: 1,
    homeCategories: ['social', 'experimental'],
    homeStyles: ['y2k', 'nostalgic', 'bold-colour'],
    homePlatforms: ['ios', 'responsive-web'],
    homeIndustries: ['media', 'lifestyle'],
  },
  {
    username: 'marc_essel',
    displayName: 'Marc Essel',
    bio: 'Modular design systems for sprawling SaaS surface areas.',
    websitePath: 'marcessel',
    popularity: 1,
    homeCategories: ['web-apps', 'dashboards'],
    homeStyles: ['modular', 'responsive', 'sans-serif'],
    homePlatforms: ['desktop-web', 'responsive-web'],
    homeIndustries: ['saas', 'fintech'],
  },
  {
    username: 'zoe_harp',
    displayName: 'Zoe Harp',
    bio: 'Maximalist branding for festivals and late-night radio shows.',
    websitePath: 'zoeharp',
    popularity: 0,
    homeCategories: ['branding', 'editorial'],
    homeStyles: ['maximalist', 'bold-colour', 'typographic'],
    homePlatforms: ['brand-identity', 'print'],
    homeIndustries: ['media', 'lifestyle'],
  },
  {
    username: 'nate_wick',
    displayName: 'Nate Wick',
    bio: 'Retro web experiments that still pass a contrast check.',
    websitePath: 'natewick',
    popularity: 0,
    homeCategories: ['experimental', 'web-apps'],
    homeStyles: ['retro', 'nostalgic', 'accessible'],
    homePlatforms: ['desktop-web', 'responsive-web'],
    homeIndustries: ['media', 'saas'],
  },
  {
    username: 'lila_crow',
    displayName: 'Lila Crow',
    bio: 'Soft wellness apps with patient, spoken microcopy.',
    websitePath: 'lilacrow',
    popularity: 1,
    homeCategories: ['health', 'mobile-apps'],
    homeStyles: ['soft', 'organic', 'spacious'],
    homePlatforms: ['ios', 'watch'],
    homeIndustries: ['health', 'lifestyle'],
  },
  {
    username: 'erik_palmo',
    displayName: 'Erik Palmo',
    bio: 'Neumorphic side quests and tactile payment confirmations.',
    websitePath: 'erikpalmo',
    popularity: 0,
    homeCategories: ['fintech', 'mobile-apps'],
    homeStyles: ['neumorphic', 'soft', 'mobile-first'],
    homePlatforms: ['ios', 'android'],
    homeIndustries: ['fintech', 'saas'],
  },
  {
    username: 'tara_glen',
    displayName: 'Tara Glen',
    bio: 'Travel editorial sites that feel like dog-eared guidebooks.',
    websitePath: 'taraglen',
    popularity: 1,
    homeCategories: ['travel', 'editorial'],
    homeStyles: ['editorial', 'photography-led', 'serif'],
    homePlatforms: ['responsive-web', 'print'],
    homeIndustries: ['travel', 'media'],
  },
  {
    username: 'ben_ochre',
    displayName: 'Ben Ochre',
    bio: 'Conversion-minded storefronts with human product photography.',
    websitePath: 'benochre',
    popularity: 1,
    homeCategories: ['ecommerce', 'branding'],
    homeStyles: ['conversion-focused', 'photography-led', 'minimal'],
    homePlatforms: ['responsive-web', 'ios'],
    homeIndustries: ['ecommerce', 'lifestyle'],
  },
  {
    username: 'nouria_vale',
    displayName: 'Nouria Vale',
    bio: 'Content-first publishing tools for independent magazines.',
    websitePath: 'nouriavale',
    popularity: 0,
    homeCategories: ['editorial', 'web-apps'],
    homeStyles: ['content-first', 'typographic', 'serif'],
    homePlatforms: ['desktop-web', 'responsive-web'],
    homeIndustries: ['media', 'education'],
  },
  {
    username: 'cole_ryss',
    displayName: 'Cole Ryss',
    bio: 'Futuristic speculative UI — still usable on a train.',
    websitePath: 'coleryss',
    popularity: 0,
    homeCategories: ['experimental', 'dashboards'],
    homeStyles: ['futuristic', 'dark', 'motion-led'],
    homePlatforms: ['desktop-web', 'tablet'],
    homeIndustries: ['saas', 'media'],
  },
  {
    username: 'amina_shof',
    displayName: 'Amina Shof',
    bio: 'Accessible civic dashboards for neighbourhood programmes.',
    websitePath: 'aminashof',
    popularity: 1,
    homeCategories: ['dashboards', 'web-apps'],
    homeStyles: ['accessible', 'high-contrast', 'functional'],
    homePlatforms: ['responsive-web', 'tablet'],
    homeIndustries: ['education', 'saas'],
  },
  {
    username: 'drew_pelt',
    displayName: 'Drew Pelt',
    bio: 'One-design-wonder — exploring a single brutalist portfolio idea.',
    websitePath: 'drewpelt',
    popularity: 0,
    homeCategories: ['portfolios', 'experimental'],
    homeStyles: ['brutalist', 'monochrome', 'typographic'],
    homePlatforms: ['responsive-web', 'brand-identity'],
    homeIndustries: ['media', 'lifestyle'],
  },
  {
    username: 'haja_stone',
    displayName: 'Haja Stone',
    bio: 'Card-heavy social products with deliberately small navigation.',
    websitePath: 'hajastone',
    popularity: 1,
    homeCategories: ['social', 'mobile-apps'],
    homeStyles: ['card-ui', 'minimal-navigation', 'mobile-first'],
    homePlatforms: ['android', 'ios'],
    homeIndustries: ['media', 'lifestyle'],
  },
  {
    username: 'pearl_ivin',
    displayName: 'Pearl Ivin',
    bio: 'Onboarding sequences that respect the first ten seconds.',
    websitePath: 'pearlivin',
    popularity: 1,
    homeCategories: ['mobile-apps', 'web-apps'],
    homeStyles: ['onboarding', 'spacious', 'soft'],
    homePlatforms: ['ios', 'responsive-web'],
    homeIndustries: ['saas', 'health'],
  },
  {
    username: 'gil_torren',
    displayName: 'Gil Torren',
    bio: 'Empty states, paywalls, and the awkward middle of subscription UX.',
    websitePath: 'giltorren',
    popularity: 0,
    homeCategories: ['web-apps', 'fintech'],
    homeStyles: ['empty-state', 'paywall', 'functional'],
    homePlatforms: ['responsive-web', 'desktop-web'],
    homeIndustries: ['saas', 'fintech'],
  },
];

export const CONSUMER_PERSONAS = [
  {
    username: 'viewer_atlas',
    displayName: 'Atlas Viewer',
    bio: 'Collecting dashboards and spare swiss layouts.',
    taste: 'data' as const,
  },
  {
    username: 'viewer_haze',
    displayName: 'Haze Viewer',
    bio: 'Soft wellness screens and quiet travel sites.',
    taste: 'soft' as const,
  },
  {
    username: 'viewer_ink',
    displayName: 'Ink Viewer',
    bio: 'Editorial type and portfolio photography.',
    taste: 'editorial' as const,
  },
  {
    username: 'viewer_bolt',
    displayName: 'Bolt Viewer',
    bio: 'Commerce and fintech with sharp hierarchy.',
    taste: 'commerce' as const,
  },
  {
    username: 'viewer_loom',
    displayName: 'Loom Viewer',
    bio: 'Experimental and brutalist rabbit holes.',
    taste: 'experimental' as const,
  },
  {
    username: 'viewer_pine',
    displayName: 'Pine Viewer',
    bio: 'Health apps that do not feel clinical.',
    taste: 'health' as const,
  },
  {
    username: 'viewer_mesa',
    displayName: 'Mesa Viewer',
    bio: 'Social products and playful onboarding.',
    taste: 'social' as const,
  },
  {
    username: 'viewer_glen',
    displayName: 'Glen Viewer',
    bio: 'Brand systems and luxury storefronts.',
    taste: 'brand' as const,
  },
  {
    username: 'viewer_tide',
    displayName: 'Tide Viewer',
    bio: 'Travel planning UX and ferry timetables.',
    taste: 'travel' as const,
  },
  {
    username: 'viewer_ember',
    displayName: 'Ember Viewer',
    bio: 'Mobile-first product screens with breathing room.',
    taste: 'mobile' as const,
  },
];

export const DESIGN_BLUEPRINTS = blueprintsJson as DesignBlueprint[];

export const TASTE_PRESETS: Record<
  (typeof CONSUMER_PERSONAS)[number]['taste'],
  {
    preferred_categories: string[];
    preferred_styles: string[];
    preferred_platforms: string[];
    preferred_industries: string[];
    preferred_colour_families: string[];
    disliked_styles: string[];
    disliked_tags: string[];
    exploration_level: 'focused' | 'balanced' | 'adventurous';
    include_ai_assisted: boolean;
    include_fully_ai_generated: boolean;
  }
> = {
  data: {
    preferred_categories: ['dashboards', 'fintech', 'web-apps'],
    preferred_styles: ['data-dense', 'grid-based', 'swiss', 'functional'],
    preferred_platforms: ['desktop-web', 'responsive-web'],
    preferred_industries: ['saas', 'fintech'],
    preferred_colour_families: ['cool-greys', 'ink-black', 'forest'],
    disliked_styles: ['maximalist', 'y2k', 'playful'],
    disliked_tags: ['y2k', 'maximalist', 'playful'],
    exploration_level: 'focused',
    include_ai_assisted: true,
    include_fully_ai_generated: false,
  },
  soft: {
    preferred_categories: ['health', 'travel', 'mobile-apps'],
    preferred_styles: ['soft', 'organic', 'spacious', 'muted-colour'],
    preferred_platforms: ['ios', 'responsive-web'],
    preferred_industries: ['health', 'travel', 'lifestyle'],
    preferred_colour_families: ['warm-neutrals', 'soft-pink', 'forest'],
    disliked_styles: ['brutalist', 'industrial', 'high-contrast'],
    disliked_tags: ['brutalist', 'industrial'],
    exploration_level: 'balanced',
    include_ai_assisted: true,
    include_fully_ai_generated: true,
  },
  editorial: {
    preferred_categories: ['editorial', 'portfolios', 'branding'],
    preferred_styles: ['editorial', 'serif', 'photography-led', 'typographic'],
    preferred_platforms: ['responsive-web', 'print'],
    preferred_industries: ['media', 'lifestyle'],
    preferred_colour_families: ['warm-neutrals', 'ink-black', 'ochre'],
    disliked_styles: ['neumorphic', 'data-dense'],
    disliked_tags: ['data-dense', 'neumorphic'],
    exploration_level: 'balanced',
    include_ai_assisted: false,
    include_fully_ai_generated: false,
  },
  commerce: {
    preferred_categories: ['ecommerce', 'fintech', 'web-apps'],
    preferred_styles: ['conversion-focused', 'functional', 'minimal', 'responsive'],
    preferred_platforms: ['responsive-web', 'ios'],
    preferred_industries: ['ecommerce', 'fintech', 'saas'],
    preferred_colour_families: ['cool-greys', 'ink-black', 'slate-blue'],
    disliked_styles: ['hand-drawn', 'y2k'],
    disliked_tags: ['hand-drawn', 'y2k'],
    exploration_level: 'focused',
    include_ai_assisted: true,
    include_fully_ai_generated: true,
  },
  experimental: {
    preferred_categories: ['experimental', 'social', 'branding'],
    preferred_styles: ['brutalist', 'experimental-navigation', 'futuristic', 'maximalist'],
    preferred_platforms: ['desktop-web', 'responsive-web'],
    preferred_industries: ['media', 'saas'],
    preferred_colour_families: ['ink-black', 'ochre', 'terracotta'],
    disliked_styles: ['soft', 'neumorphic'],
    disliked_tags: ['soft', 'neumorphic'],
    exploration_level: 'adventurous',
    include_ai_assisted: true,
    include_fully_ai_generated: true,
  },
  health: {
    preferred_categories: ['health', 'mobile-apps'],
    preferred_styles: ['accessible', 'soft', 'spacious', 'onboarding'],
    preferred_platforms: ['ios', 'tablet'],
    preferred_industries: ['health', 'education'],
    preferred_colour_families: ['warm-neutrals', 'forest', 'soft-pink'],
    disliked_styles: ['dark', 'maximalist'],
    disliked_tags: ['dark', 'maximalist'],
    exploration_level: 'focused',
    include_ai_assisted: true,
    include_fully_ai_generated: false,
  },
  social: {
    preferred_categories: ['social', 'mobile-apps', 'experimental'],
    preferred_styles: ['playful', 'card-ui', 'bold-colour', 'onboarding'],
    preferred_platforms: ['ios', 'android'],
    preferred_industries: ['media', 'lifestyle'],
    preferred_colour_families: ['soft-pink', 'ochre', 'slate-blue'],
    disliked_styles: ['industrial', 'data-dense'],
    disliked_tags: ['industrial', 'data-dense'],
    exploration_level: 'adventurous',
    include_ai_assisted: true,
    include_fully_ai_generated: true,
  },
  brand: {
    preferred_categories: ['branding', 'ecommerce', 'portfolios'],
    preferred_styles: ['luxury', 'geometric', 'monochrome', 'minimal'],
    preferred_platforms: ['brand-identity', 'responsive-web'],
    preferred_industries: ['lifestyle', 'ecommerce', 'media'],
    preferred_colour_families: ['ink-black', 'warm-neutrals', 'ochre'],
    disliked_styles: ['playful', 'y2k'],
    disliked_tags: ['y2k', 'playful'],
    exploration_level: 'balanced',
    include_ai_assisted: false,
    include_fully_ai_generated: false,
  },
  travel: {
    preferred_categories: ['travel', 'editorial', 'mobile-apps'],
    preferred_styles: ['organic', 'photography-led', 'editorial', 'muted-colour'],
    preferred_platforms: ['ios', 'responsive-web'],
    preferred_industries: ['travel', 'lifestyle', 'media'],
    preferred_colour_families: ['slate-blue', 'warm-neutrals', 'forest'],
    disliked_styles: ['data-dense', 'industrial'],
    disliked_tags: ['data-dense'],
    exploration_level: 'balanced',
    include_ai_assisted: true,
    include_fully_ai_generated: true,
  },
  mobile: {
    preferred_categories: ['mobile-apps', 'health', 'social'],
    preferred_styles: ['mobile-first', 'spacious', 'minimal-navigation', 'soft'],
    preferred_platforms: ['ios', 'android'],
    preferred_industries: ['lifestyle', 'health', 'saas'],
    preferred_colour_families: ['warm-neutrals', 'forest', 'cool-greys'],
    disliked_styles: ['data-dense', 'maximalist'],
    disliked_tags: ['data-dense'],
    exploration_level: 'focused',
    include_ai_assisted: true,
    include_fully_ai_generated: true,
  },
};
